version: "3"

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_pdbd
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    ports:
      - 6001:6001
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - app-network
    depends_on:
      - db
      - redis

  # Nginx
  webserver:
   image: nginx:alpine
   container_name: webserver_pdbd
   restart: unless-stopped
   tty: true
   ports:
    - 8080:80
    - 443:443
   volumes:
    - ./:/var/www
    - ./nginx/conf.d/:/etc/nginx/conf.d/
   networks:
    - app-network 

  # Mysql
  db:
    image: mysql:5.7
    container_name: db_pdbd
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pdbd
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Redis
  redis:
    image: redis:5.0.0-alpine
    restart: always
    container_name: redis-pdbd
    ports:
      - 6379:6379
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local